CC=clang
CFLAGS=-Wall -Wextra -pedantic -Wconversion \
			 -Wunreachable-code -Wswitch-enum -Wno-gnu

EXE=run

all: main
	$(EXE)

install: main
	cp ./$(EXE) $(HOME)/bin/$(EXE)

main: main.c
	$(CC) main.c -o $(EXE) $(CFLAGS)

clean:
	rm -rf $(EXE)
